-- MySQL Script generated by MySQL Workbench
-- Thu Feb 11 15:42:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `librarydb` ;

-- -----------------------------------------------------
-- Table `librarydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`authors` (
  `AuthorId` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(50) NULL DEFAULT NULL,
  `Lastname` VARCHAR(50) NULL DEFAULT NULL,
  `Bio` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`AuthorId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`books` (
  `BookId` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NULL DEFAULT NULL,
  `Year` INT NULL DEFAULT NULL,
  `ISBN` VARCHAR(60) NULL DEFAULT NULL,
  `Summary` VARCHAR(300) NULL DEFAULT NULL,
  `Image` VARCHAR(1000) NULL DEFAULT NULL,
  `Price` DECIMAL(18,2) NULL DEFAULT NULL,
  `AuthorId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`BookId`),
  INDEX `FK_Books_Authors` (`AuthorId` ASC) VISIBLE,
  CONSTRAINT `FK_Books_Authors`
    FOREIGN KEY (`AuthorId`)
    REFERENCES `librarydb`.`authors` (`AuthorId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarydb`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`logs` (
  `LogId` INT NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(2000) NULL DEFAULT NULL,
  `Date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `LogType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`LogId`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `librarydb`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`pages` (
  `PageId` INT NOT NULL AUTO_INCREMENT,
  `PageNumber` INT NULL DEFAULT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `BookId` INT NOT NULL,
  PRIMARY KEY (`PageId`),
  INDEX `FK_Book_Pages` (`BookId` ASC) VISIBLE,
  CONSTRAINT `FK_Book_Pages`
    FOREIGN KEY (`BookId`)
    REFERENCES `librarydb`.`books` (`BookId`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE USER 'java'@'localhost' IDENTIFIED BY 'java@123';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
